#!/bin/bash
#LR
for runtype in closed_singlet open_singlet open_triplet 
do
    nosetests -v test_findif_lr_$runtype.py  2>&1 | tee test_findif_lr_$runtype.log
done

#QR
for runtype in closed_singlet closed_triplet open_singlet open_triplet 
do
    nosetests -v test_findif_qr_$runtype.py  2>&1 | tee test_findif_qr_$runtype.log
done

#CR
for runtype in closed_singlet
do
    nosetests -v test_findif_cr_$runtype.py  2>&1 | tee test_findif_cr_$runtype.log
done
